# shellmind fish integration
# ---------------------------------------------------------------------
# Generated by `shellmind init fish`.
#
# fish has no ghost-text layer, so shellmind binds Alt keys:
#
#   Alt+P   natural-language command palette
#   Alt+E   explain the current command line
#   Alt+F   fix the current command line / last failure
#   Alt+R   semantic history search
#
# fish's own autosuggestion (from fish's built-in history) keeps working
# alongside shellmind; semantic search is a superset available on Alt+R.
# ---------------------------------------------------------------------

set -l _sm_bin (command -v sm; or command -v shellmind)
if test -z "$_sm_bin"
    echo "shellmind: neither 'sm' nor 'shellmind' found on PATH" >&2
    exit 1
end
set -g _sm_bin

function __sm_palette --description "shellmind natural-language palette"
    set -l sel (eval $_sm_bin palette --shell fish --buffer (commandline) </dev/tty 2>/dev/null)
    if test -n "$sel"
        commandline -r $sel
    end
    commandline -f repaint
end

function __sm_explain --description "explain the current command line"
    set -l out (eval $_sm_bin explain --buffer (commandline) 2>/dev/null)
    if test -n "$out"
        echo ""
        printf '%s\n' $out
    end
    commandline -f repaint
end

function __sm_fix --description "fix the current command line / last failure"
    set -l sel (eval $_sm_bin fix --buffer (commandline) --menu </dev/tty 2>/dev/null)
    if test -n "$sel"
        commandline -r $sel
    end
    commandline -f repaint
end

function __sm_history --description "semantic shell history search"
    set -l sel (eval $_sm_bin history --menu </dev/tty 2>/dev/null)
    if test -n "$sel"
        commandline -r $sel
    end
    commandline -f repaint
end

function __sm_record --on-event fish_postexec
    # fish does not expose exit codes in postexec; shellmind records the
    # command (exit code unknown) and captures failures through `sm fix`
    # inference instead.
    eval $_sm_bin record 0 -- "$argv[1]" &>/dev/null &
end

function __sm_aliases --on-event fish_prompt
    # Refresh the alias cache at most once a minute.
    if test -z "$_sm_alias_at"; or test (math (date +%s) - $_sm_alias_at) -gt 60
        set -g _sm_alias_at (date +%s)
        begin
            abbr --show 2>/dev/null
            alias 2>/dev/null
        end > "${SHELLMIND_HOME:-$HOME/.config/shellmind}/aliases.txt" &
    end
end

function fish_user_key_bindings
    bind \ep __sm_palette
    bind \ee __sm_explain
    bind \ef __sm_fix
    bind \er __sm_history
end

# fish >= 3.1 also supports the event-based binding hook; re-bind on
# every new keymap to stay active after `fish_vi_key_bindings` etc.
function __sm_bind_all --on-event fish_mode_change
    bind \ep __sm_palette
    bind \ee __sm_explain
    bind \ef __sm_fix
    bind \er __sm_history
end
