# shellmind zsh integration
# ---------------------------------------------------------------------
# Generated by `shellmind init zsh` — do not edit here; configure via
#   ~/.config/shellmind/config.toml  ([keybindings] section)
# and re-run:  eval "$(shellmind init zsh)"
#
# Layout:
#   Ctrl+Space   natural-language command palette
#   Ctrl+E       explain the current command line
#   Ctrl+F       fix the current command line / last failure
#   Ctrl+R       semantic history search
#   Right / End  accept inline ghost suggestion
#   Ctrl+Right   accept one word of the suggestion
#   Ctrl+G       dismiss the ghost suggestion
#   (set SHELLMIND_TAB_ACCEPT=1 to also accept on Tab)
# ---------------------------------------------------------------------

# --- locate the binary -------------------------------------------------
if (( $+commands[sm] )); then
  typeset -g _SM_BIN=sm
elif (( $+commands[shellmind] )); then
  typeset -g _SM_BIN=shellmind
else
  print -u2 "shellmind: neither 'sm' nor 'shellmind' found on PATH"
  return 1 2>/dev/null || exit 1
fi

typeset -g _SM_GHOST_BUFFER=""
typeset -g _SM_LAST_CMD=""
typeset -g _SM_ALIAS_AT=0

_sm() { "$_SM_BIN" "$@" }

# --- ghost text ---------------------------------------------------------
# Fetched on every line redraw (zsh >= 5.9). With the daemon running this
# is a warm-cache Unix-socket round trip; without it, `sm` computes the
# suggestion directly (SQLite prefix query).
_sm_fetch_ghost() {
  local buffer="$1"
  typeset -g _SM_GHOST_BUFFER=""
  [[ -z "$buffer" || "$buffer" == $'\n'* ]] && { POSTDISPLAY=""; return }
  (( ${#buffer} > 300 )) && return
  local ghost
  ghost=$(_sm complete --shell zsh --buffer "$buffer" --ghost 2>/dev/null)
  _SM_GHOST_BUFFER="$buffer"
  if [[ -n "$ghost" ]]; then
    if [[ "$buffer" == *" " ]]; then
      POSTDISPLAY="$ghost"
    else
      POSTDISPLAY="$ghost"
    fi
  else
    POSTDISPLAY=""
  fi
}

_sm_line_redraw() {
  # Only fetch when the buffer changed; keeps keystrokes cheap.
  if [[ "$BUFFER" != "$_SM_GHOST_BUFFER" ]]; then
    _sm_fetch_ghost "$BUFFER"
  fi
  return 0
}

autoload -Uz add-zle-hook-widget
add-zle-hook-widget line-pre-redraw _sm_line_redraw 2>/dev/null || true

# --- accepting suggestions ----------------------------------------------
_sm-accept-whole() {
  if [[ -n "$POSTDISPLAY" ]]; then
    BUFFER="$BUFFER$POSTDISPLAY"
    POSTDISPLAY=""
    CURSOR=${#BUFFER}
    _SM_GHOST_BUFFER=""
  else
    zle .accept-line 2>/dev/null || zle accept-line
  fi
}
zle -N _sm-accept-whole

_sm-forward-char() {
  if [[ -n "$POSTDISPLAY" ]]; then
    _sm-accept-whole
  else
    zle .forward-char
  fi
}
zle -N _sm-forward-char

_sm-end-of-line() {
  if [[ -n "$POSTDISPLAY" ]]; then
    _sm-accept-whole
  else
    zle .end-of-line
  fi
}
zle -N _sm-end-of-line

_sm-accept-word() {
  if [[ -n "$POSTDISPLAY" ]]; then
    local rest="$POSTDISPLAY"
    local word="${rest%% *}"
    if [[ "$rest" == *" "* ]]; then
      BUFFER="$BUFFER$word "
      POSTDISPLAY="${rest#* }"
      CURSOR=${#BUFFER}
    else
      BUFFER="$BUFFER$rest"
      POSTDISPLAY=""
      CURSOR=${#BUFFER}
    fi
    _SM_GHOST_BUFFER="$BUFFER"
  else
    zle .forward-word
  fi
}
zle -N _sm-accept-word

_sm-cancel() {
  POSTDISPLAY=""
  _SM_GHOST_BUFFER=""
}
zle -N _sm-cancel

bindkey "${SHELLMIND_KEY_ACCEPT_RIGHT:-^F}" _sm-forward-char
bindkey "${SHELLMIND_KEY_ACCEPT_END:-^E}" _sm-end-of-line
bindkey "${SHELLMIND_KEY_ACCEPT_WORD:-^X^F}" _sm-accept-word
bindkey "${SHELLMIND_KEY_CANCEL:-^G}" _sm-cancel
if [[ "${SHELLMIND_TAB_ACCEPT:-0}" == "1" ]]; then
  bindkey "\t" _sm-accept-whole
fi

# --- Ctrl+Space: natural-language palette -------------------------------
_sm_palette() {
  local result
  result=$(_sm palette --shell zsh --buffer "$BUFFER" </dev/tty 2>/dev/null)
  if [[ -n "$result" ]]; then
    BUFFER="$result"
    CURSOR=${#BUFFER}
  fi
  zle reset-prompt
}
zle -N _sm_palette
bindkey "${SHELLMIND_KEY_PALETTE:-^@}" _sm_palette

# --- Ctrl+E: explain current command ------------------------------------
_sm_explain() {
  local out
  out=$(_sm explain --buffer "$BUFFER" 2>/dev/null)
  zle -I
  if [[ -n "$out" ]]; then
    print ""
    print -r -- "$out"
    print -n "Press any key to continue…"
    read -k 1 -s
    print ""
  fi
  zle reset-prompt
}
zle -N _sm_explain
bindkey "${SHELLMIND_KEY_EXPLAIN:-^[e}" _sm_explain

# --- Ctrl+F: fix current command or last failure -------------------------
_sm_fix() {
  local result
  result=$(_sm fix --buffer "$BUFFER" --menu </dev/tty 2>/dev/null)
  if [[ -n "$result" ]]; then
    BUFFER="$result"
    CURSOR=${#BUFFER}
  fi
  zle reset-prompt
}
zle -N _sm_fix
bindkey "${SHELLMIND_KEY_FIX:-^[f}" _sm_fix

# --- Ctrl+R: semantic history search -------------------------------------
_sm_history_search() {
  local result
  result=$(_sm history --menu </dev/tty 2>/dev/null)
  if [[ -n "$result" ]]; then
    BUFFER="$result"
    CURSOR=${#BUFFER}
    zle reset-prompt
  else
    zle history-incremental-search-backward
  fi
}
zle -N _sm_history_search
bindkey "${SHELLMIND_KEY_HISTORY:-^R}" _sm_history_search

# --- command recording + alias export ------------------------------------
_sm_preexec() {
  _SM_LAST_CMD="$1"
}

_sm_precmd() {
  local rc=$?
  if [[ -n "$_SM_LAST_CMD" ]]; then
    (_sm record "$rc" -- "$_SM_LAST_CMD" &>/dev/null &)!
    _SM_LAST_CMD=""
  fi
  # Refresh the alias cache at most once per minute.
  if (( SECONDS - _SM_ALIAS_AT > 60 )); then
    _SM_ALIAS_AT=$SECONDS
    (_sm aliases > "${SHELLMIND_HOME:-$HOME/.config/shellmind}/aliases.txt" &>/dev/null &)!
  fi
}

typeset -ga preexec_functions
typeset -ga precmd_functions
(( ${preexec_functions[(Ie)_sm_preexec]:-0} )) || preexec_functions+=(_sm_preexec)
(( ${precmd_functions[(Ie)_sm_precmd]:-0} )) || precmd_functions+=(_sm_precmd)

# Enable fish-style autosuggest colors for the ghost text.
zstyle ':completion:*' menu select 2>/dev/null || true
