# shellmind bash integration
# ---------------------------------------------------------------------
# Generated by `shellmind init bash`.
#
# bash has no ghost-text layer, so shellmind integrates through
# readline widgets (`bind -x`):
#
#   Ctrl+Space   completion menu for the current line
#   Alt+E        explain the current command line
#   Alt+F        fix the current command line / last failure
#   Alt+R        semantic history search
#
# All key bindings can be overridden with SHELLMIND_KEY_* variables.
# ---------------------------------------------------------------------

if command -v sm >/dev/null 2>&1; then
  _SM_BIN=sm
elif command -v shellmind >/dev/null 2>&1; then
  _SM_BIN=shellmind
else
  echo "shellmind: neither 'sm' nor 'shellmind' found on PATH" >&2
  return 1 2>/dev/null || exit 1
fi

_sm() { "$_SM_BIN" "$@"; }

# --- Ctrl+Space: completion menu -----------------------------------------
_sm_menu() {
  local sel
  sel=$(_sm complete --shell bash --buffer "$READLINE_LINE" --cursor "$READLINE_POINT" --menu </dev/tty 2>/dev/null)
  if [[ -n "$sel" ]]; then
    READLINE_LINE="$sel"
    READLINE_POINT=${#READLINE_LINE}
  fi
}
bind -x "\"\C-@\": _sm_menu"

# --- Alt+E: explain current command ---------------------------------------
_sm_explain_widget() {
  local out
  out=$(_sm explain --buffer "$READLINE_LINE" 2>/dev/null)
  if [[ -n "$out" ]]; then
    echo ""
    printf '%s\n' "$out"
    echo -n "Press any key to continue…"
    read -n 1 -s
    echo ""
  fi
}
bind -x "\"\ee\": _sm_explain_widget"

# --- Alt+F: fix current command / last failure -----------------------------
_sm_fix_widget() {
  local sel
  sel=$(_sm fix --buffer "$READLINE_LINE" --menu </dev/tty 2>/dev/null)
  if [[ -n "$sel" ]]; then
    READLINE_LINE="$sel"
    READLINE_POINT=${#READLINE_LINE}
  fi
}
bind -x "\"\ef\": _sm_fix_widget"

# --- Alt+R: semantic history search ----------------------------------------
_sm_history_widget() {
  local sel
  sel=$(_sm history --menu </dev/tty 2>/dev/null)
  if [[ -n "$sel" ]]; then
    READLINE_LINE="$sel"
    READLINE_POINT=${#READLINE_LINE}
  fi
}
bind -x "\"\er\": _sm_history_widget"

# --- command recording ------------------------------------------------------
# DEBUG trap captures each command before execution; PROMPT_COMMAND records
# its exit status right before the next prompt is drawn.
declare -g _SM_LAST_CMD=""

trap 'declare -g _SM_LAST_CMD="$BASH_COMMAND"' DEBUG

_sm_bash_precmd() {
  local rc=$?
  if [[ -n "${_SM_LAST_CMD:-}" ]]; then
    (_sm record "$rc" -- "$_SM_LAST_CMD" &>/dev/null &)
    declare -g _SM_LAST_CMD=""
  fi
  # Refresh the alias cache at most once per minute.
  if [[ -z "${_SM_ALIAS_AT:-}" ]] || (( SECONDS - _SM_ALIAS_AT > 60 )); then
    _SM_ALIAS_AT=$SECONDS
    (alias -p > "${SHELLMIND_HOME:-$HOME/.config/shellmind}/aliases.txt" 2>/dev/null &)
  fi
  return $rc
}

PROMPT_COMMAND="_sm_bash_precmd${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
